repos:
  - repo: https://github.com/oryon-dominik/pre-commit-alacritty-os-specific-shell-hook
    rev: 1.0.0
    hooks:
      - id: alacritty-os-specific-shell
        args: [--posix=C:/Program Files/PowerShell/7/pwsh.exe --posix=/bin/fish]
