# This is just a reminder for the user to add some personal settings to the
# system.. could be automated in lengthy automation scripts.. yawn.
Write-Host "Adding Oryon's Taste to the system..."
Write-Host ""
Write-Host ""
Write-Host "Add to quick access ..."""
Write-Host '(new-object -com shell.application).Namespace("$env:DOTFILES").Self.InvokeVerb("pintohome")'
Write-Host '(new-object -com shell.application).Namespace("$env:JOURNAL_HOME").Self.InvokeVerb("pintohome")'
Write-Host '(new-object -com shell.application).Namespace("$env:PROJECTS").Self.InvokeVerb("pintohome")'
Write-Host ""
Write-Host ""
Write-Host "Music Production..."
Write-Host "MUSIC_PRODUCTION_HOME=c:\music\"
Write-Host "MUSIC_SESSIONS_HOME=$env:MUSIC_PRODUCTION_HOME\sessions"
Write-Host '(new-object -com shell.application).Namespace("$env:MUSIC_PRODUCTION_HOME").Self.InvokeVerb("pintohome")'
Write-Host ""
Write-Host ""
Write-Host "directories and symlinks"
Write-Host "C:\screenshots"
Write-Host "C:\cloud"
Write-Host "+ symlink from actual cloud (install and integrate gdrive) to C:\cloud"
Write-Host ""
Write-Host ""
Write-Host "python global venvs"
Write-Host '(new-object -com shell.application).Namespace("$env:USERPROFILE\$env:GLOBAL_PYTHON_VENVS").Self.InvokeVerb("pintohome")'
Write-Host ""
Write-Host ""
Write-Host "images"
Write-Host "background pic, depending screen resolution -> shared\files\images\backgrounds"
Write-Host ""
Write-Host ""
Write-Host "Taskbar"
Write-Host "styling of taskbar (position on top) - windows 11 needs a tool for this to work"
Write-Host "see: ~\.dotfiles\shared\files\ep_setup.exe"
Write-Host ""
Write-Host "# Get explorer patcher to restore explorers work functionality on windows 11.."
Write-Host "# These UXers of Windows are a bunch of jerks. They keep removing features that"
Write-Host "# are useful to users since the beginning of Windows."
Write-Host "# ..."
Write-Host "# https://github.com/valinet/ExplorerPatcher"
Write-Host "# https://www.deskmodder.de/wiki/index.php?title=Start_aus_dem_Datei_Explorer_entfernen_Windows_11"
Write-Host ""
Write-Host "# To remove the annoying additional categories from explorer: "
Write-Host "# add aministrator privileges (full access)"
Write-Host "# (right click permissions, enhanced, add, enter your username, check names, ok, ok)"
Write-Host "# now give the administrator full access"
Write-Host "# - catalogue"
Write-Host "#   Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}"
Write-Host "#   System.IsPinnedToNameSpaceTree = 0"
Write-Host "# - start"
Write-Host "#   Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}"
Write-Host "#   System.IsPinnedToNameSpaceTree = 0"
Write-Host ""
Write-Host ""
Write-Host "processes"
Write-Host "run processes (popup for windows terminal with ahk) backup background tasks running a script in dotfiles"
Write-Host ""
Write-Host ""
Write-Host "brwoser"
Write-Host "chrome settings and login, including lastpass and personal + business profiles"
Write-Host ""
Write-Host ""
Write-Host "vscode"
Write-Host "vscode login via github and settings sync"
Write-Host ""
Write-Host ""
Write-Host "Screenshot prints via flameshot"
Write-Host 'windows -> settings -> "Barrierefreiheit" -> "Tastatur" -> ""Verwenden der Drucktaste zum Öffnen der Bildschirmaufnahme"'
Write-Host ""
Write-Host ""
Write-Host "Deactivate telemetry and diagnostics.."
