name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - "trunk"
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "downloads/visualization.svg"

          excluded_paths: "ignore,.github"